package hr.unipu.polyling.baza;

public class PunjenjeBaze {


    public static void puniKategorije(Baza baza) {

        //prvo isprazniti tablicu ako postoje kategorije (korisno zbog refreshanja)
        baza.obrisiKategorije();

        baza.dodajKategoriju("Basic", "Osnove", "phrases");
        baza.dodajKategoriju("Time", "Vrijeme", "time");
        baza.dodajKategoriju("Weather", "Vremenska prognoza", "weather");
        baza.dodajKategoriju("Directions", "Upute", "directions");
        baza.dodajKategoriju("Emergency", "SOS", "emergency");
        baza.dodajKategoriju("Food", "Hrana", "food");
        baza.dodajKategoriju("Love", "Ljubav", "love");
        baza.dodajKategoriju("Money", "Novac", "money");
        baza.dodajKategoriju("Conversations", "Razgovori", "people");
        baza.dodajKategoriju("Shopping", "Kupovina", "shopping");

    }

    public static void puniFraze(Baza baza) {
        baza.obrisiFraze();

        baza.dodajFrazu("What do you do?", "S čime se bavite?", baza.getKategorijaIdByNaziv("Business"));
        baza.dodajFrazu("What do you do for a living?", "Što radite?", baza.getKategorijaIdByNaziv("Business"));
        baza.dodajFrazu("What sort of work do you do?", "Kojom vrstom posla se bavite?", baza.getKategorijaIdByNaziv("Business"));
        baza.dodajFrazu("What line of work are you in?", "Kojom linijom posla se bavite?", baza.getKategorijaIdByNaziv("Business"));
        baza.dodajFrazu("I'm a …", "Ja sam …", baza.getKategorijaIdByNaziv("Business"));
        baza.dodajFrazu("Teacher", "Učitelj/učiteljica", baza.getKategorijaIdByNaziv("Business"));
        baza.dodajFrazu("Student", "Student/studentica", baza.getKategorijaIdByNaziv("Business"));
        baza.dodajFrazu("Doctor", "Doktor/doktorica", baza.getKategorijaIdByNaziv("Business"));
        baza.dodajFrazu("I work as a …", "Radim kao …", baza.getKategorijaIdByNaziv("Business"));
        baza.dodajFrazu("Journalist", "Novinar/novinarka", baza.getKategorijaIdByNaziv("Business"));
        baza.dodajFrazu("Programmer", "Programer/programerka", baza.getKategorijaIdByNaziv("Business"));
        baza.dodajFrazu("I work in …", "Radim u …", baza.getKategorijaIdByNaziv("Business"));
        baza.dodajFrazu("Television", "Televizijskoj kući", baza.getKategorijaIdByNaziv("Business"));
        baza.dodajFrazu("Publishing", "Izdavaštvu", baza.getKategorijaIdByNaziv("Business"));
        baza.dodajFrazu("PR (public relations)", "Odnosima s javnošću", baza.getKategorijaIdByNaziv("Business"));
        baza.dodajFrazu("Sales", "Prodaji", baza.getKategorijaIdByNaziv("Business"));
        baza.dodajFrazu("IT", "Telekomunikacijama", baza.getKategorijaIdByNaziv("Business"));
        baza.dodajFrazu("I work with …", "Radim sa …", baza.getKategorijaIdByNaziv("Business"));
        baza.dodajFrazu("Computers", "Kompjuterima", baza.getKategorijaIdByNaziv("Business"));
        baza.dodajFrazu("Children with disabilities", "Djecom sa teškoćama", baza.getKategorijaIdByNaziv("Business"));
        baza.dodajFrazu("I stay at home and look after the children", "Ostajem kući i brinem se o djeci", baza.getKategorijaIdByNaziv("Business"));
        baza.dodajFrazu("I'm a housewife", "Kućanica sam", baza.getKategorijaIdByNaziv("Business"));
        baza.dodajFrazu("What's the time?", "Koliko je sati?", baza.getKategorijaIdByNaziv("Time"));
        baza.dodajFrazu("What time is it?", "Koliko je sati?", baza.getKategorijaIdByNaziv("Time"));
        baza.dodajFrazu("Could you tell me the time, please?", "Možete li mi reći koliko je sati, molim vas?", baza.getKategorijaIdByNaziv("Time"));
        baza.dodajFrazu("Do you happen to have the time?", "Znate li koliko je sati?", baza.getKategorijaIdByNaziv("Time"));
        baza.dodajFrazu("Do you know what time it is?", "Znaš li koliko je sati?", baza.getKategorijaIdByNaziv("Time"));
        baza.dodajFrazu("It's …", "Sad je …", baza.getKategorijaIdByNaziv("Time"));
        baza.dodajFrazu("Exactly ...", "Točno …", baza.getKategorijaIdByNaziv("Time"));
        baza.dodajFrazu("About ...", "Otprilike …", baza.getKategorijaIdByNaziv("Time"));
        baza.dodajFrazu("Almost ...", "Skoro …", baza.getKategorijaIdByNaziv("Time"));
        baza.dodajFrazu("Just gone ...", "Upravo je prošlo …", baza.getKategorijaIdByNaziv("Time"));
        baza.dodajFrazu("One o'clock", "Jedan sat", baza.getKategorijaIdByNaziv("Time"));
        baza.dodajFrazu("Two o'clock", "Dva sata", baza.getKategorijaIdByNaziv("Time"));
        baza.dodajFrazu("Three o'clock", "Tri sata", baza.getKategorijaIdByNaziv("Time"));
        baza.dodajFrazu("Four o'clock", "Četiri sata", baza.getKategorijaIdByNaziv("Time"));
        baza.dodajFrazu("Five o'clock", "Pet sati", baza.getKategorijaIdByNaziv("Time"));
        baza.dodajFrazu("Six o'clock", "Šest sati", baza.getKategorijaIdByNaziv("Time"));
        baza.dodajFrazu("Seven o'clock", "Sedam sati", baza.getKategorijaIdByNaziv("Time"));
        baza.dodajFrazu("Eight o'clock", "Osam sati", baza.getKategorijaIdByNaziv("Time"));
        baza.dodajFrazu("Nine o'clock", "Devet sati", baza.getKategorijaIdByNaziv("Time"));
        baza.dodajFrazu("Ten o'clock", "Deset sati", baza.getKategorijaIdByNaziv("Time"));
        baza.dodajFrazu("Eleven o'clock", "Jedanaest sati", baza.getKategorijaIdByNaziv("Time"));
        baza.dodajFrazu("Twelve o'clock", "Dvanaest sati", baza.getKategorijaIdByNaziv("Time"));
        baza.dodajFrazu("Quarter past …", "Kvarat poslije …", baza.getKategorijaIdByNaziv("Time"));
        baza.dodajFrazu("One", "Jedan", baza.getKategorijaIdByNaziv("Time"));
        baza.dodajFrazu("Two", "Dva", baza.getKategorijaIdByNaziv("Time"));
        baza.dodajFrazu("Three", "Tri", baza.getKategorijaIdByNaziv("Time"));
        baza.dodajFrazu("Half past …", "Pola sata nakon …", baza.getKategorijaIdByNaziv("Time"));
        baza.dodajFrazu("One", "Jedan i pol", baza.getKategorijaIdByNaziv("Time"));
        baza.dodajFrazu("Two", "Dva i pol", baza.getKategorijaIdByNaziv("Time"));
        baza.dodajFrazu("Three", "Tri i pol", baza.getKategorijaIdByNaziv("Time"));
        baza.dodajFrazu("Five past one", "Jedan i pet", baza.getKategorijaIdByNaziv("Time"));
        baza.dodajFrazu("Ten past one", "Jedan i deset", baza.getKategorijaIdByNaziv("Time"));
        baza.dodajFrazu("Twenty past one", "Jedan i dvadeset", baza.getKategorijaIdByNaziv("Time"));
        baza.dodajFrazu("Twenty-five past one", "Jedan i dvadeset-pet", baza.getKategorijaIdByNaziv("Time"));
        baza.dodajFrazu("Five to two", "Pet do dva", baza.getKategorijaIdByNaziv("Time"));
        baza.dodajFrazu("Ten to two", "Deset do dva", baza.getKategorijaIdByNaziv("Time"));
        baza.dodajFrazu("Twenty to two", "Dvadeset do dva", baza.getKategorijaIdByNaziv("Time"));
        baza.dodajFrazu("Twenty-five to two", "Dvadeset-pet do dva", baza.getKategorijaIdByNaziv("Time"));
        baza.dodajFrazu("Ten fifteen", "Deset i petnaest", baza.getKategorijaIdByNaziv("Time"));
        baza.dodajFrazu("Ten thirty", "Deset i pol", baza.getKategorijaIdByNaziv("Time"));
        baza.dodajFrazu("Ten forty-five", "Deset i četrdeset-pet", baza.getKategorijaIdByNaziv("Time"));
        baza.dodajFrazu("Ten am", "Deset ujutro", baza.getKategorijaIdByNaziv("Time"));
        baza.dodajFrazu("Six pm", "Šest sati", baza.getKategorijaIdByNaziv("Time"));
        baza.dodajFrazu("Ten am", "Deset ujutro", baza.getKategorijaIdByNaziv("Time"));
        baza.dodajFrazu("Six pm", "Šest sati", baza.getKategorijaIdByNaziv("Time"));
        baza.dodajFrazu("Noon ili midday", "Podne ili dvanaest sati", baza.getKategorijaIdByNaziv("Time"));
        baza.dodajFrazu("Midnight", "Ponoć", baza.getKategorijaIdByNaziv("Time"));
        baza.dodajFrazu("Do you take credit cards?", "Primate li kreditne kartice?", baza.getKategorijaIdByNaziv("Money"));
        baza.dodajFrazu("I'll pay in cash", "Platit ću gotovinom", baza.getKategorijaIdByNaziv("Money"));
        baza.dodajFrazu("I'll pay by card", "Platit ću karticom", baza.getKategorijaIdByNaziv("Money"));
        baza.dodajFrazu("Could I have a receipt, please?", "Mogu li dobiti račun, molim?", baza.getKategorijaIdByNaziv("Money"));
        baza.dodajFrazu("I'd like to return this", "Želim vratiti ovo", baza.getKategorijaIdByNaziv("Money"));
        baza.dodajFrazu("I'd like to change this for a different size", "Želim zamijeniti ovo za drugu veličinu", baza.getKategorijaIdByNaziv("Money"));
        baza.dodajFrazu("Could I have a refund?", "Mogu li dobiti povrat novca?", baza.getKategorijaIdByNaziv("Money"));
        baza.dodajFrazu("Have you got the receipt?", "Imate li račun?", baza.getKategorijaIdByNaziv("Money"));
        baza.dodajFrazu("Enter your PIN", "Unesite vaš PIN", baza.getKategorijaIdByNaziv("Money"));
        baza.dodajFrazu("Please wait", "Molimo pričekajte", baza.getKategorijaIdByNaziv("Money"));
        baza.dodajFrazu("Remove card", "Izvadite karticu", baza.getKategorijaIdByNaziv("Money"));
        baza.dodajFrazu("Signature", "Potpis", baza.getKategorijaIdByNaziv("Money"));
        baza.dodajFrazu("What's the expiry date?", "Koji je datum isteka valjanosti?", baza.getKategorijaIdByNaziv("Money"));
        baza.dodajFrazu("What's the start date?", "Koji je početan datum?", baza.getKategorijaIdByNaziv("Money"));
        baza.dodajFrazu("What's the security number on the back?", "Koji je broj za sigurnosnu provjeru sa stražnje strane?", baza.getKategorijaIdByNaziv("Money"));
        baza.dodajFrazu("Here", "Ovdje", baza.getKategorijaIdByNaziv("Directions"));
        baza.dodajFrazu("There", "Tamo", baza.getKategorijaIdByNaziv("Directions"));
        baza.dodajFrazu("Everywhere", "Svugdje", baza.getKategorijaIdByNaziv("Directions"));
        baza.dodajFrazu("Nowhere", "Nigdje", baza.getKategorijaIdByNaziv("Directions"));
        baza.dodajFrazu("Somewhere", "Negdje", baza.getKategorijaIdByNaziv("Directions"));
        baza.dodajFrazu("Excuse me, could you tell me how to get to …?", "Oprostite, da li mi možete reći kako doći do …?", baza.getKategorijaIdByNaziv("Directions"));
        baza.dodajFrazu("The bus station", "Autobusne stanice", baza.getKategorijaIdByNaziv("Directions"));
        baza.dodajFrazu("Excuse me, do you know where the … is?", "Oprostite, da li znate gdje se … nalazi?", baza.getKategorijaIdByNaziv("Directions"));
        baza.dodajFrazu("Post office", "Pošta", baza.getKategorijaIdByNaziv("Directions"));
        baza.dodajFrazu("I'm sorry, I don't know", "Žao mi je, ne znam", baza.getKategorijaIdByNaziv("Directions"));
        baza.dodajFrazu("Sorry, I'm not from around here", "Žao mi je, nisam odavde", baza.getKategorijaIdByNaziv("Directions"));
        baza.dodajFrazu("I'm sorry, I don't know", "Žao mi je, ne znam", baza.getKategorijaIdByNaziv("Directions"));
        baza.dodajFrazu("Sorry, I'm not from around here", "Žao mi je, nisam odavde", baza.getKategorijaIdByNaziv("Directions"));
        baza.dodajFrazu("I'm looking for …", "Tražim …", baza.getKategorijaIdByNaziv("Directions"));
        baza.dodajFrazu("This address", "Ovu adresu", baza.getKategorijaIdByNaziv("Directions"));
        baza.dodajFrazu("Are we on the right road for …?", "Jesmo li na ispravnoj cesti prema …?", baza.getKategorijaIdByNaziv("Directions"));
        baza.dodajFrazu("Pula", "Puli", baza.getKategorijaIdByNaziv("Directions"));
        baza.dodajFrazu("Is this the right way for …?", "Da li je ovo ispravan put prema …?", baza.getKategorijaIdByNaziv("Directions"));
        baza.dodajFrazu("Zagreb", "Zagrebu", baza.getKategorijaIdByNaziv("Directions"));
        baza.dodajFrazu("Do you have a map?", "Imaš li mapu?", baza.getKategorijaIdByNaziv("Directions"));
        baza.dodajFrazu("Can you show me on the map?", "Možeš mi pokazati na mapi?", baza.getKategorijaIdByNaziv("Directions"));
        baza.dodajFrazu("How far is it?", "Koliko je udaljeno?", baza.getKategorijaIdByNaziv("Directions"));
        baza.dodajFrazu("How far is it to …?", "Koliko je daleko do …?", baza.getKategorijaIdByNaziv("Directions"));
        baza.dodajFrazu("The airport", "Aerodroma", baza.getKategorijaIdByNaziv("Directions"));
        baza.dodajFrazu("How far is it to … from here?", "Koliko daleko je … odavde?", baza.getKategorijaIdByNaziv("Directions"));
        baza.dodajFrazu("The beach", "Plaža", baza.getKategorijaIdByNaziv("Directions"));
        baza.dodajFrazu("Is it far?", "Da li je daleko?", baza.getKategorijaIdByNaziv("Directions"));
        baza.dodajFrazu("Is it a long way?", "Da li je dugačak put?", baza.getKategorijaIdByNaziv("Directions"));
        baza.dodajFrazu("It's …", "To …", baza.getKategorijaIdByNaziv("Directions"));
        baza.dodajFrazu("Not far", "Nije daleko", baza.getKategorijaIdByNaziv("Directions"));
        baza.dodajFrazu("Quite close", "Je prilično blizu", baza.getKategorijaIdByNaziv("Directions"));
        baza.dodajFrazu("Quite a long way", "Je prilično daleko", baza.getKategorijaIdByNaziv("Directions"));
        baza.dodajFrazu("A long way on foot", "Je prilično daleko pješice", baza.getKategorijaIdByNaziv("Directions"));
        baza.dodajFrazu("A long way to walk", "Je dugačak put za hodanje", baza.getKategorijaIdByNaziv("Directions"));
        baza.dodajFrazu("About a mile from here", "Je otprilike milju odavde (jedna milja je otprilike 1.6 kilometara)", baza.getKategorijaIdByNaziv("Directions"));
        baza.dodajFrazu("Do you have any snacks?", "Imate li kakve grickalice?", baza.getKategorijaIdByNaziv("Food"));
        baza.dodajFrazu("Do you have any sandwiches?", "Imate li kakve sendviče?", baza.getKategorijaIdByNaziv("Food"));
        baza.dodajFrazu("Do you serve food?", "Poslužujete li hranu?", baza.getKategorijaIdByNaziv("Food"));
        baza.dodajFrazu("What time does the kitchen close?", "Kada se kuhinja zatvara?", baza.getKategorijaIdByNaziv("Food"));
        baza.dodajFrazu("Are you still serving food?", "Poslužujete li još uvijek hranu?", baza.getKategorijaIdByNaziv("Food"));
        baza.dodajFrazu("A packet of crisps, please", "Paket čipsa, molim", baza.getKategorijaIdByNaziv("Food"));
        baza.dodajFrazu("What flavour would you like?", "Koji okus želite?", baza.getKategorijaIdByNaziv("Food"));
        baza.dodajFrazu("Ready salted", "Slani", baza.getKategorijaIdByNaziv("Food"));
        baza.dodajFrazu("Cheese and onion", "Sir i luk", baza.getKategorijaIdByNaziv("Food"));
        baza.dodajFrazu("Salt and vinegar", "Sir i ocat", baza.getKategorijaIdByNaziv("Food"));
        baza.dodajFrazu("What sort of sandwiches do you have?", "Kakve sendviče imate?", baza.getKategorijaIdByNaziv("Food"));
        baza.dodajFrazu("Do you have any hot food?", "Imate li kakve tople obroke?", baza.getKategorijaIdByNaziv("Food"));
        baza.dodajFrazu("Today's specials are on the board", "Današnji specijaliteti su na ploči", baza.getKategorijaIdByNaziv("Food"));
        baza.dodajFrazu("What sort of sandwiches do you have?", "Kakve sendviče imate?", baza.getKategorijaIdByNaziv("Food"));
        baza.dodajFrazu("Do you have any hot food?", "Imate li kakve tople obroke?", baza.getKategorijaIdByNaziv("Food"));
        baza.dodajFrazu("Today's specials are on the board", "Današnji specijaliteti su na ploči", baza.getKategorijaIdByNaziv("Food"));
        baza.dodajFrazu("Is it table service or self-service?", "Poslužuje li se za stolom ili je riječ o samoposluzi?", baza.getKategorijaIdByNaziv("Food"));
        baza.dodajFrazu("What can I get you?", "Što vam mogu donijeti?", baza.getKategorijaIdByNaziv("Food"));
        baza.dodajFrazu("Would you like anything to eat?", "Želite li pojesti nešto?", baza.getKategorijaIdByNaziv("Food"));
        baza.dodajFrazu("Could we see a menu, please?", "Možemo li vidjeti cjenik, molim?", baza.getKategorijaIdByNaziv("Food"));
        baza.dodajFrazu("Eat in or take-away?", "Za ovdje ili za van?", baza.getKategorijaIdByNaziv("Food"));
        baza.dodajFrazu("I'd like …", "Želim …", baza.getKategorijaIdByNaziv("Food"));
        baza.dodajFrazu("That piece of cheese", "Taj komad sira", baza.getKategorijaIdByNaziv("Food"));
        baza.dodajFrazu("A slice of pizza", "Krišku pizze", baza.getKategorijaIdByNaziv("Food"));
        baza.dodajFrazu("Six slices of ham", "Šest kriški šunke", baza.getKategorijaIdByNaziv("Food"));
        baza.dodajFrazu("Some olives", "Malo maslina", baza.getKategorijaIdByNaziv("Food"));
        baza.dodajFrazu("How much would you like?", "Koliko biste željeli?", baza.getKategorijaIdByNaziv("Food"));
        baza.dodajFrazu("300 grams", "300 grama", baza.getKategorijaIdByNaziv("Food"));
        baza.dodajFrazu("Half a kilo", "Pola kile", baza.getKategorijaIdByNaziv("Food"));
        baza.dodajFrazu("Two pounds", "Dvije funte ", baza.getKategorijaIdByNaziv("Food"));
        baza.dodajFrazu("OK", "OK", baza.getKategorijaIdByNaziv("Basic"));
        baza.dodajFrazu("Of course", "Naravno", baza.getKategorijaIdByNaziv("Basic"));
        baza.dodajFrazu("Of course not", "Naravno da ne", baza.getKategorijaIdByNaziv("Basic"));
        baza.dodajFrazu("That's fine", "U redu je", baza.getKategorijaIdByNaziv("Basic"));
        baza.dodajFrazu("That's right", "Tako je", baza.getKategorijaIdByNaziv("Basic"));
        baza.dodajFrazu("Sure", "Naravno", baza.getKategorijaIdByNaziv("Basic"));
        baza.dodajFrazu("Certainly", "Svakako", baza.getKategorijaIdByNaziv("Basic"));
        baza.dodajFrazu("Definitely", "Definitivno", baza.getKategorijaIdByNaziv("Basic"));
        baza.dodajFrazu("Absolutely", "Apsolutno", baza.getKategorijaIdByNaziv("Basic"));
        baza.dodajFrazu("As soon as possible", "Čim prije moguće", baza.getKategorijaIdByNaziv("Basic"));
        baza.dodajFrazu("That's enough", "To je dovoljno", baza.getKategorijaIdByNaziv("Basic"));
        baza.dodajFrazu("It doesn't matter", "Nema veze", baza.getKategorijaIdByNaziv("Basic"));
        baza.dodajFrazu("It's not important", "Nije važno", baza.getKategorijaIdByNaziv("Basic"));
        baza.dodajFrazu("It's not serious", "Nije ozbiljno", baza.getKategorijaIdByNaziv("Basic"));
        baza.dodajFrazu("It's not worth it", "Nije vrijedno toga", baza.getKategorijaIdByNaziv("Basic"));
        baza.dodajFrazu("I'm in a hurry", "U žurbi sam", baza.getKategorijaIdByNaziv("Basic"));
        baza.dodajFrazu("I've got to go", "Moram ići", baza.getKategorijaIdByNaziv("Basic"));
        baza.dodajFrazu("I'm going out", "Idem van", baza.getKategorijaIdByNaziv("Basic"));
        baza.dodajFrazu("Sleep well", "Lijepo spavaj", baza.getKategorijaIdByNaziv("Basic"));
        baza.dodajFrazu("Same to you!", "Također", baza.getKategorijaIdByNaziv("Basic"));
        baza.dodajFrazu("Me too", "I ja", baza.getKategorijaIdByNaziv("Basic"));
        baza.dodajFrazu("Not bad", "Nije loše", baza.getKategorijaIdByNaziv("Basic"));
        baza.dodajFrazu("I like …", "Sviđa mi se …", baza.getKategorijaIdByNaziv("Basic"));
        baza.dodajFrazu("Him", "On", baza.getKategorijaIdByNaziv("Basic"));
        baza.dodajFrazu("Her", "Ona", baza.getKategorijaIdByNaziv("Basic"));
        baza.dodajFrazu("It", "Ono", baza.getKategorijaIdByNaziv("Basic"));
        baza.dodajFrazu("I don't like …", "Ne sviđa mi se …", baza.getKategorijaIdByNaziv("Basic"));
        baza.dodajFrazu("Him", "On", baza.getKategorijaIdByNaziv("Basic"));
        baza.dodajFrazu("Her", "Ona", baza.getKategorijaIdByNaziv("Basic"));
        baza.dodajFrazu("It", "Ono", baza.getKategorijaIdByNaziv("Basic"));
        baza.dodajFrazu("Look!", "Gle!", baza.getKategorijaIdByNaziv("Basic"));
        baza.dodajFrazu("Great!", "Odlično!", baza.getKategorijaIdByNaziv("Basic"));
        baza.dodajFrazu("Come on!", "Hajde!", baza.getKategorijaIdByNaziv("Basic"));
        baza.dodajFrazu("Only joking! ili just kidding!", "Šalim se! ili samo se šalim!", baza.getKategorijaIdByNaziv("Basic"));
        baza.dodajFrazu("Bless you!", "Nazdravlje! (nakon što netko kihne)", baza.getKategorijaIdByNaziv("Basic"));
        baza.dodajFrazu("That's funny!", "To je smiješno!", baza.getKategorijaIdByNaziv("Basic"));
        baza.dodajFrazu("That's life!", "To je život!", baza.getKategorijaIdByNaziv("Basic"));
        baza.dodajFrazu("Damn it!", "K vragu!", baza.getKategorijaIdByNaziv("Basic"));
        baza.dodajFrazu("What's your name?", "Kako se zoveš?", baza.getKategorijaIdByNaziv("Conversations"));
        baza.dodajFrazu("My name's …", "Zovem se …", baza.getKategorijaIdByNaziv("Conversations"));
        baza.dodajFrazu("Chris", "Chris", baza.getKategorijaIdByNaziv("Conversations"));
        baza.dodajFrazu("Emily", "Emily", baza.getKategorijaIdByNaziv("Conversations"));
        baza.dodajFrazu("This is …", "Ovo je …", baza.getKategorijaIdByNaziv("Conversations"));
        baza.dodajFrazu("Lucy", "Lucy", baza.getKategorijaIdByNaziv("Conversations"));
        baza.dodajFrazu("My wife", "Moja žena", baza.getKategorijaIdByNaziv("Conversations"));
        baza.dodajFrazu("My husband", "Moj muž", baza.getKategorijaIdByNaziv("Conversations"));
        baza.dodajFrazu("My boyfriend", "Moj dečko", baza.getKategorijaIdByNaziv("Conversations"));
        baza.dodajFrazu("My girlfriend", "Moja djevojka", baza.getKategorijaIdByNaziv("Conversations"));
        baza.dodajFrazu("My son", "Moj sin", baza.getKategorijaIdByNaziv("Conversations"));
        baza.dodajFrazu("My daughter", "Moja kćer", baza.getKategorijaIdByNaziv("Conversations"));
        baza.dodajFrazu("Do you know each other?", "Poznajete li se?", baza.getKategorijaIdByNaziv("Conversations"));
        baza.dodajFrazu("Nice to meet you", "Drago mi je upoznati vas", baza.getKategorijaIdByNaziv("Conversations"));
        baza.dodajFrazu("Pleased to meet you", "Zadovoljstvo mi je upoznati vas", baza.getKategorijaIdByNaziv("Conversations"));
        baza.dodajFrazu("How do you know each other?", "Kako se poznajete?", baza.getKategorijaIdByNaziv("Conversations"));
        baza.dodajFrazu("We work together", "Radimo zajedno", baza.getKategorijaIdByNaziv("Conversations"));
        baza.dodajFrazu("We used to work together", "Nekad smo radili zajedno", baza.getKategorijaIdByNaziv("Conversations"));
        baza.dodajFrazu("We were at school together", "Išli smo zajedno u školu", baza.getKategorijaIdByNaziv("Conversations"));
        baza.dodajFrazu("We're at university together", "Studiramo zajedno", baza.getKategorijaIdByNaziv("Conversations"));
        baza.dodajFrazu("We went to university together", "Studirali smo zajedno", baza.getKategorijaIdByNaziv("Conversations"));
        baza.dodajFrazu("Through friends", "Preko prijatelja", baza.getKategorijaIdByNaziv("Conversations"));
        baza.dodajFrazu("Call an ambulance!", "Zovite hitnu pomoć!", baza.getKategorijaIdByNaziv("Emergency"));
        baza.dodajFrazu("I need a doctor", "Trebam doktora", baza.getKategorijaIdByNaziv("Emergency"));
        baza.dodajFrazu("There's been an accident", "Dogodila se nesreća", baza.getKategorijaIdByNaziv("Emergency"));
        baza.dodajFrazu("Please hurry!", "Molim, požurite!", baza.getKategorijaIdByNaziv("Emergency"));
        baza.dodajFrazu("I've cut myself", "Porezao/porezala sam se!", baza.getKategorijaIdByNaziv("Emergency"));
        baza.dodajFrazu("I've burnt myself", "Opekao/opekla sam se!", baza.getKategorijaIdByNaziv("Emergency"));
        baza.dodajFrazu("Are you OK?", "Da li si dobro?", baza.getKategorijaIdByNaziv("Emergency"));
        baza.dodajFrazu("Is everyone OK?", "Da li su svi dobro?", baza.getKategorijaIdByNaziv("Emergency"));
        baza.dodajFrazu("I'd like to report a theft", "Želim prijaviti krađu", baza.getKategorijaIdByNaziv("Emergency"));
        baza.dodajFrazu("My car's been broken into", "Netko je provalio u moj auto", baza.getKategorijaIdByNaziv("Emergency"));
        baza.dodajFrazu("Fire!", "Požar!", baza.getKategorijaIdByNaziv("Emergency"));
        baza.dodajFrazu("Call the fire brigade!", "Zovite vatrogasce!", baza.getKategorijaIdByNaziv("Emergency"));
        baza.dodajFrazu("Can you smell burning?", "Osjetite li dim?", baza.getKategorijaIdByNaziv("Emergency"));
        baza.dodajFrazu("There's a fire", "Tamo je požar", baza.getKategorijaIdByNaziv("Emergency"));
        baza.dodajFrazu("The building's on fire", "Zgrada gori", baza.getKategorijaIdByNaziv("Emergency"));
        baza.dodajFrazu("Stop, thief!", "Stani, lopov!", baza.getKategorijaIdByNaziv("Emergency"));
        baza.dodajFrazu("Call the police!", "Zovite policiju!", baza.getKategorijaIdByNaziv("Emergency"));
        baza.dodajFrazu("My wallet's been stolen", "Moj novčanik je ukraden", baza.getKategorijaIdByNaziv("Emergency"));
        baza.dodajFrazu("My purse has been stolen", "Moja torbica je ukradena", baza.getKategorijaIdByNaziv("Emergency"));
        baza.dodajFrazu("My handbag's been stolen", "Moja torba je ukradena", baza.getKategorijaIdByNaziv("Emergency"));
        baza.dodajFrazu("My laptop's been stolen", "Moj laptop je ukraden", baza.getKategorijaIdByNaziv("Emergency"));
        baza.dodajFrazu("My phone's been stolen", "Moj mobitel je ukraden", baza.getKategorijaIdByNaziv("Emergency"));
        baza.dodajFrazu("I've been mugged", "Opljačkan/opljačkana sam", baza.getKategorijaIdByNaziv("Emergency"));
        baza.dodajFrazu("I've been attacked", "Napadnut/napadnuta sam", baza.getKategorijaIdByNaziv("Emergency"));
        baza.dodajFrazu("What's the weather like?", "Kakvo je vrijeme?", baza.getKategorijaIdByNaziv("Weather"));
        baza.dodajFrazu("It's …", "Vrijeme je …", baza.getKategorijaIdByNaziv("Weather"));
        baza.dodajFrazu("Sunny", "Sunčano", baza.getKategorijaIdByNaziv("Weather"));
        baza.dodajFrazu("Cloudy", "Oblačno", baza.getKategorijaIdByNaziv("Weather"));
        baza.dodajFrazu("Windy", "Vjetrovito", baza.getKategorijaIdByNaziv("Weather"));
        baza.dodajFrazu("Foggy", "Maglovito", baza.getKategorijaIdByNaziv("Weather"));
        baza.dodajFrazu("Stormy", "Olujno", baza.getKategorijaIdByNaziv("Weather"));
        baza.dodajFrazu("It's …", "Vrijeme je …", baza.getKategorijaIdByNaziv("Weather"));
        baza.dodajFrazu("Raining", "Kišovito", baza.getKategorijaIdByNaziv("Weather"));
        baza.dodajFrazu("Hailing", "Tuča", baza.getKategorijaIdByNaziv("Weather"));
        baza.dodajFrazu("Snowing", "Snježno", baza.getKategorijaIdByNaziv("Weather"));
        baza.dodajFrazu("What a nice day!", "Kakav predivan dan!", baza.getKategorijaIdByNaziv("Weather"));
        baza.dodajFrazu("What a beautiful day!", "Kakav prekrasan dan!", baza.getKategorijaIdByNaziv("Weather"));
        baza.dodajFrazu("It's not a very nice day", "Nije jako lijep dan", baza.getKategorijaIdByNaziv("Weather"));
        baza.dodajFrazu("What a terrible day!", "Kakav užasan dan!", baza.getKategorijaIdByNaziv("Weather"));
        baza.dodajFrazu("What miserable weather!", "Kakvo loše vrijeme", baza.getKategorijaIdByNaziv("Weather"));
        baza.dodajFrazu("It's starting to rain", "Počinje padati kiša", baza.getKategorijaIdByNaziv("Weather"));
        baza.dodajFrazu("It's stopped raining", "Prestala je kiša", baza.getKategorijaIdByNaziv("Weather"));
        baza.dodajFrazu("It's pouring with rain", "Kiša pljušti", baza.getKategorijaIdByNaziv("Weather"));
        baza.dodajFrazu("It's raining cats and dogs", "Lijeva kao iz kabla", baza.getKategorijaIdByNaziv("Weather"));
        baza.dodajFrazu("The weather's fine", "Vrijeme je u redu", baza.getKategorijaIdByNaziv("Weather"));
        baza.dodajFrazu("The sun's shining", "Sunce sja", baza.getKategorijaIdByNaziv("Weather"));
        baza.dodajFrazu("There's not a cloud in the sky", "Nema nijednog oblaka na nebu", baza.getKategorijaIdByNaziv("Weather"));
        baza.dodajFrazu("The sky's overcast", "Nebo je prekriveno", baza.getKategorijaIdByNaziv("Weather"));
        baza.dodajFrazu("It's clearing up", "Čisti se", baza.getKategorijaIdByNaziv("Weather"));
        baza.dodajFrazu("The sun's come out", "Sunce je izašlo", baza.getKategorijaIdByNaziv("Weather"));
        baza.dodajFrazu("The sun's just gone in", "Sunce je upravo zašlo", baza.getKategorijaIdByNaziv("Weather"));
        baza.dodajFrazu("There's a strong wind", "Vjetar je snažan", baza.getKategorijaIdByNaziv("Weather"));
        baza.dodajFrazu("The wind's dropped", "Vjetar je oslabio", baza.getKategorijaIdByNaziv("Weather"));
        baza.dodajFrazu("That sounds like thunder", "To zvuči kao grmljavina", baza.getKategorijaIdByNaziv("Weather"));
        baza.dodajFrazu("That's lightning", "Sijeva", baza.getKategorijaIdByNaziv("Weather"));
        baza.dodajFrazu("We had a lot of heavy rain this morning", "Jutros je jako padala kiša", baza.getKategorijaIdByNaziv("Weather"));
        baza.dodajFrazu("We haven't had any rain for a fortnight", "Kiša nije padala dva tjedna", baza.getKategorijaIdByNaziv("Weather"));
        baza.dodajFrazu("Could I try this on?", "Mogu li isprobati ovo?", baza.getKategorijaIdByNaziv("Shopping"));
        baza.dodajFrazu("Could I try these on?", "Mogu li probati ove?", baza.getKategorijaIdByNaziv("Shopping"));
        baza.dodajFrazu("Could I try these shoes on?", "Mogu li probati ove cipele?", baza.getKategorijaIdByNaziv("Shopping"));
        baza.dodajFrazu("Do you want to try it on?", "Želite li probati to?", baza.getKategorijaIdByNaziv("Shopping"));
        baza.dodajFrazu("Do you want to try them on?", "Želite li ih probati?", baza.getKategorijaIdByNaziv("Shopping"));
        baza.dodajFrazu("What size are you?", "Koja ste veličina?", baza.getKategorijaIdByNaziv("Shopping"));
        baza.dodajFrazu("What size do you take?", "Koju veličinu uzimate?", baza.getKategorijaIdByNaziv("Shopping"));
        baza.dodajFrazu("Do you have this in a size …?", "Imate li ovo u veličini …?", baza.getKategorijaIdByNaziv("Shopping"));
        baza.dodajFrazu("7", "7", baza.getKategorijaIdByNaziv("Shopping"));
        baza.dodajFrazu("Do you have these in a size …?", "Imate li ove u veličini …?", baza.getKategorijaIdByNaziv("Shopping"));
        baza.dodajFrazu("12", "12", baza.getKategorijaIdByNaziv("Shopping"));
        baza.dodajFrazu("Do you have a fitting room?", "Imate li garderobu?", baza.getKategorijaIdByNaziv("Shopping"));
        baza.dodajFrazu("Where's the fitting room?", "Gdje je garderoba?", baza.getKategorijaIdByNaziv("Shopping"));
        baza.dodajFrazu("Have you got this in a smaller size?", "Imate li ovo u manjoj veličini?", baza.getKategorijaIdByNaziv("Shopping"));
        baza.dodajFrazu("Have you got this in a larger size?", "Imate li ovo u većoj veličini?", baza.getKategorijaIdByNaziv("Shopping"));
        baza.dodajFrazu("Could you measure my …?", "Možete li izmjeriti moj/moja …?", baza.getKategorijaIdByNaziv("Shopping"));
        baza.dodajFrazu("Waist", "Struk", baza.getKategorijaIdByNaziv("Shopping"));
        baza.dodajFrazu("Neck", "Vrat", baza.getKategorijaIdByNaziv("Shopping"));
        baza.dodajFrazu("Chest", "Prsa", baza.getKategorijaIdByNaziv("Shopping"));
        baza.dodajFrazu("It's much too small", "Prilično je malo", baza.getKategorijaIdByNaziv("Shopping"));
        baza.dodajFrazu("It's a little too small", "Premalo je", baza.getKategorijaIdByNaziv("Shopping"));
        baza.dodajFrazu("It's a little too big", "Preveliko je", baza.getKategorijaIdByNaziv("Shopping"));
        baza.dodajFrazu("It's just right", "Taman je", baza.getKategorijaIdByNaziv("Shopping"));
        baza.dodajFrazu("They're just right", "Taman su", baza.getKategorijaIdByNaziv("Shopping"));
        baza.dodajFrazu("Can I buy you a drink?", "Mogu li te počastiti pićem?", baza.getKategorijaIdByNaziv("Love"));
        baza.dodajFrazu("Would you like a drink?", "Želiš li piće?", baza.getKategorijaIdByNaziv("Love"));
        baza.dodajFrazu("Can I get you a drink?", "Mogu li ti donijeti piće?", baza.getKategorijaIdByNaziv("Love"));
        baza.dodajFrazu("Are you on your own?", "Jesi li sam/sama?", baza.getKategorijaIdByNaziv("Love"));
        baza.dodajFrazu("Would you like to join us?", "Želiš nam se pridružiti?", baza.getKategorijaIdByNaziv("Love"));
        baza.dodajFrazu("Do you mind if I join you?", "Da li smeta ako vam se pridružim?", baza.getKategorijaIdByNaziv("Love"));
        baza.dodajFrazu("Do you mind if we join you?", "Da li smeta ako vam se mi pridružimo?", baza.getKategorijaIdByNaziv("Love"));
        baza.dodajFrazu("Do you come here often?", "Dolaziš li ovdje često?", baza.getKategorijaIdByNaziv("Love"));
        baza.dodajFrazu("Is this your first time here?", "Je li ovo prvi put da si ovdje?", baza.getKategorijaIdByNaziv("Love"));
        baza.dodajFrazu("Have you been here before?", "Jesi li već bio/bila ovdje prije?", baza.getKategorijaIdByNaziv("Love"));
        baza.dodajFrazu("Would you like to dance?", "Želiš li plesati?", baza.getKategorijaIdByNaziv("Love"));
        baza.dodajFrazu("You look great", "Izgledaš odlično", baza.getKategorijaIdByNaziv("Love"));
        baza.dodajFrazu("You look very nice tonight", "Izgledaš jako lijepo večeras", baza.getKategorijaIdByNaziv("Love"));
        baza.dodajFrazu("I like your outfit", "Sviđa mi se tvoje odijelo", baza.getKategorijaIdByNaziv("Love"));
        baza.dodajFrazu("You're beautiful", "Prekrasna si (govori se ženi)", baza.getKategorijaIdByNaziv("Love"));
        baza.dodajFrazu("You're really good-looking", "Jako dobro izgledaš", baza.getKategorijaIdByNaziv("Love"));
        baza.dodajFrazu("You're really sexy", "Jako si seksi", baza.getKategorijaIdByNaziv("Love"));
        baza.dodajFrazu("You've got beautiful eyes", "Imaš prekrasne oči", baza.getKategorijaIdByNaziv("Love"));
        baza.dodajFrazu("You've got a great smile", "Imaš predivan osmijeh", baza.getKategorijaIdByNaziv("Love"));
        baza.dodajFrazu("Thanks for the compliment!", "Hvala na komplimentu", baza.getKategorijaIdByNaziv("Love"));

    }
}
